### ISSUE TITLE
create crss organization

### ISSUE THREAD

**Issue by rabutler-usbr** [BoulderCodeHub/CRSSIO#104]
Hi @crss

I was wondering if you would be willing to give up the crss username/organization as it doesn't look like you have any public repos?

We have a model (CRSS) and tons of supporting libraries, like this one, and other sub modules, so would love to wrap it all under crss. 

No problem at all if not and you are working on tons of private repos :) completely understand, but thought I'd check.

Thanks!

**Comment by crss** [comment]
Hi Alan,

thanks for your mail. But i don't want to give it up.

Sorry.

Best Regards.

Am Fr., 15. Jan. 2021 um 22:25 Uhr schrieb Alan Butler <
notifications@github.com>:

**Comment by rabutler-usbr** [comment]
@crss - no problem at all! thank you for the response.
